### ISSUE TITLE
Things deno doc should support 

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_doc#4]
- [x] reexports (`export { foo } from "./bar.ts"` and `export * from "./bar.ts"`) (#4625)
- [x] colored output (#4518)
- [x] `declare` and d.ts (#4573)
- [x] parent class information and inherited fields in classes (`class Bar extends Foo`) (#4595)
- [ ] jsdoc for fields in interfaces
- [ ] prettier jsdoc for console output (maybe https://github.com/Canop/termimad?)
- [ ] better detail output for interface
- [x] better detail output for enum (#6078)
- [ ] detail output for class fields (`deno doc deno.ns.d.ts Deno.Buffer.write`)
- [ ] parent interface information and inherited fields in interfaces (`interface Bar extends Foo`)
- [x] display all overloads in cli details view (#6186)
- [ ] exports like these: https://gist.github.com/lucacasonato/1715418303c252e5290d96051d45e8b2
- [ ] indexable types: `x?: { [key: string]: { a: number; b: number } }`

*maybe*
- [ ] 2nd level and deeper reexports

**Comment by sebastienfilion** [comment]
There are JSDoc parser available - how could we integrate them to fast-track full JSDoc support? https://deno.land/x/docable@v0.1.3

**Comment by lucacasonato** [comment]
@sebastienfilion `deno doc` is implemented and Rust so this does not help. We already have a JSDoc parser (from swc).

**Comment by sebastienfilion** [comment]
Makes sense. How can I help from here if I want all (or most) JSDoc tags to be correctly parsed by Deno doc?

**Comment by zhmushan** [comment]
> Here the cause is that we don't support the `export { foo, bar };` syntax. We only support exporting at declaration at the moment (so `export const foo = "abc";`)

In this case, swc ast cannot get the declaration source....

**Comment by lucacasonato** [comment]
Yeah - we will need to do this one in a special way. We first need to visit all of the unexported declarations and save them with their identifier in a HashMap/Vec, and have a second Vec to collect all of the unresolved `export { foo, bar }` identifiers. Then at the end we could look up all of the identifiers from the second Vec, in the first HashMap/Vec.

**Comment by josh-hemphill** [comment]
I'm not sure if I need to open a separate issue, is `@deno-types` supported yet? 
I've got a library that uses a `mod.ts` and its `/dist` to provide support for deno, but deno doc fails.
https://doc.deno.land/https/deno.land/x/valivar/mod.ts

**Comment by uki00a** [comment]
I'll try to work on `jsdoc for fields in interfaces` and `detail output for class fields` :slightly_smiling_face:

**Comment by opiation** [comment]
Hey @lucacasonato, I'm not sure if this use case would be included in _jsdoc for fields in interfaces_ from the issue description but I've noticed that types defined with `@typedef` are not displayed in console output under `deno doc`.

For example,

```js
// identity.js

/**
 * @template T
 * @typedef {Object} Identity
 * @property {<U>(f: (value: T) => U) => Identity<U>} map
 */

/**
 * @template T
 * @param {T} value
 * @return {Identity<T>}
 */
export function of(value) {
  return {
    map(f) {
      return of(f(value));
    }
  };
}
```

```sh
$ deno doc identity.js

function of(value)
  @template T
  @param {T} value
  @return {Identity<T>}
```

Importing the `Identity` type from a `.ts` file shows that the type is indeed exported by the `.js` file.

```ts
// example.ts

import type { Identity } from './identity.js'; // works fine
```

It does not show up in `deno doc identity.js` though.  If the type or interface were defined in a `.ts` file, it would appear in the output as:

```ts
// identity.ts

export interface Identity<T> {
  map<U>(f: (value: T) => U): Identity<U>
}
```

```sh
$ deno doc identity.ts

interface Identity<T>

  map(f: (value: T) => U): Identity<U>
```

Can types defined with JSDoc's `@typedef` be exposed by `deno doc`?  Also, should this be tracked as a separate issue, added to the list in the description or inferred by _jsdoc for fields in interfaces_?

**Comment by bartlomieju** [comment]
@opiation thanks for valueable feedback, please open a separate issue for this request.

**Comment by bartlomieju** [comment]
I'm going to close this issue in favor of #111
